### ISSUE TITLE
自动化MQTT消息为纯数字把发送邮件失败

### ISSUE THREAD

**Issue by qibao07** [shaonianzhentan/smtp#1]
自动化配置

```
alias: MQTT发送邮件
description: ""
trigger:
  - platform: mqtt
    topic: test/sendemail
condition: []
action:
  - service: smtp.notify
    data:
      message: "{{ trigger.payload }}"
      email: ***@foxmail.com
mode: queued
max: 10
```

这时向主题`test/sendemail`推送消息，当为纯数字时（如：123）邮件未送达，非纯数字（如：123a）可正常送达。
